using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FMScout
{
    public static class CustomDataColumns
    {
        public static List<String> playerColumns = new List<string>{
            "S",
            "ID",
            "Full Name",
            "Nation",
            "Club",
            "Team Squad",
            "Position",
            "Age",
            "CA",
            "PA",
            "ADiff",
            "Best PR",
            "Best PR%",
            "Current Value",
            "Sale Value",
            "Contract Started",
            "Contract Expiring",
            "Current Wage",
            "World Reputation",
            "National Reputation",
            "Local Reputation",
            "Corners",
            "Crossing",
            "Dribbling",
            "Finishing",
            "First Touch",
            "Free Kicks",
            "Heading",
            "Long Shots",
            "Long Throws",
            "Marking",
            "Passing",
            "Penalty Taking",
            "Tackling",
            "Technique",
            "Acceleration",
            "Agility",
            "Balance",
            "Jumping",
            "Natural Fitness",
            "Pace",
            "Stamina",
            "Strength",
            "Left Foot",
            "Right Foot",
            "Aggression",
            "Anticipation",
            "Bravery",
            "Composure",
            "Concentration",
            "Creativity",
            "Decisions",
            "Determination",
            "Flair",
            "Influence",
            "Off The Ball",
            "Positioning",
            "Team Work",
            "WorkRate",
            "Consistency",
            "Dirtyness",
            "Important Matches",
            "Injury Proneness",
            "Versatility",
            "Aerial Ability",
            "Command Of Area",
            "Communication",
            "Eccentricity",
            "Handling",
            "Kicking",
            "One On Ones",
            "Reflexes",
            "Rushing Out",
            "Tendency To Punch",
            "Throwing",
            "Adaptability",
            "Ambition",
            "Controversy",
            "Loyalty",
            "Pressure",
            "Professionalism",
            "Sportsmanship",
            "Temperament"
        };
		
		public static List<String> staffColumns = new List<string>{
			"ID",
            "Full Name",
            "Nation",
            "Club",
            "Role",
            "Age",
            "CA",
            "PA",
            "ADiff",
            "Best CR",
            "Best CR Stars",
            "Contract Started",
            "Contract Expiring",
            "Current Wage",
            "World Reputation",
            "National Reputation",
            "Local Reputation",
            "Depth",
            "Directness",
            "Flamboyancy",
            "Flexibility",
            "Free Roles",
            "Marking",
            "Offside",
            "Pressing",
            "Sitting Back",
            "Tempo",
            "Use Of Playmaker",
            "Use Of Substitutions",
            "Width",
            "Adaptability",
            "Ambition",
            "Controversy",
            "Determination",
            "Loyalty",
            "Pressure",
            "Professionalism",
            "Sportsmanship",
            //"Temperament",
            "Judging Player Ability",
            "Judging Player Potential",
            "Level Of Discipline",
            "Motivating",
            "Physiotherapy",
            "Tactical Knowledge",
            "Attacking",
            "Defending",
            "Fitness",
            "Goalkeepers",
            "Mental",
            "Player",
            "Tactical",
            "Technical",
            "Man Management",
            "Working With Youngsters",
            "Buying Players",
            "Hardness Of Training",
            "Mind Games",
            "Squad Rotation",
            "Business",
            "Interference",
            "Patience",
            "Resources"
		};
		
		public static List<String> teamColumns = new List<string>{
			"ID",
            "Name",
            "Nation",
            "Reputation",
            "Status",
            "Stadium",
            "Transfer Budget",
            "Remaining Budget",
            "Wage Budget",
            "Wage Used",
            "Budget Balance",
            "Transfer Revenue Available",
            "Current Affiliated Clubs",
            "Max Affiliated Clubs",
            "Training Facilities",
            "Youth Facilities",
            "Maximum Attendance",
            "Average Attendance",
            "Minimum Attendance",
            "Decay",
            "Field Width",
            "Field Length",
            "Current Capacity ",
            "Seating Capacity",
            "Expansion Capacity",
            "Used Capacity"
		};

        public static List<String> shortlistColumns = new List<string>{
            "ID",
            "Full Name",
            "Nation",
            "Club",
            "Team Squad",
            "Position",
            "Age",
            "CA",
            "PA",
            "ADiff",
            "Best PR",
            "Best PR%",
            "Current Value",
            "Sale Value",
            "Contract Started",
            "Contract Expiring",
            "Current Wage",
            "World Reputation",
            "National Reputation",
            "Local Reputation",
            "Corners",
            "Crossing",
            "Dribbling",
            "Finishing",
            "First Touch",
            "Free Kicks",
            "Heading",
            "Long Shots",
            "Long Throws",
            "Marking",
            "Passing",
            "Penalty Taking",
            "Tackling",
            "Technique",
            "Acceleration",
            "Agility",
            "Balance",
            "Jumping",
            "Natural Fitness",
            "Pace",
            "Stamina",
            "Strength",
            "Left Foot",
            "Right Foot",
            "Aggression",
            "Anticipation",
            "Bravery",
            "Composure",
            "Concentration",
            "Creativity",
            "Decisions",
            "Determination",
            "Flair",
            "Influence",
            "Off The Ball",
            "Positioning",
            "Team Work",
            "WorkRate",
            "Consistency",
            "Dirtyness",
            "Important Matches",
            "Injury Proneness",
            "Versatility",
            "Aerial Ability",
            "Command Of Area",
            "Communication",
            "Eccentricity",
            "Handling",
            "Kicking",
            "One On Ones",
            "Reflexes",
            "Rushing Out",
            "Tendency To Punch",
            "Throwing",
            "Adaptability",
            "Ambition",
            "Controversy",
            "Loyalty",
            "Pressure",
            "Professionalism",
            "Sportsmanship",
            "Temperament"
        };
		
    }
}
